default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: railsdev
  password: railsdev

development:
  <<: *default
  database: payments_dev

test:
  <<: *default
  database: payments_test
